ALTER TABLE KLF_OIP ADD COLUMN IF NOT EXISTS FULL_NAME VARCHAR(512);

-- LOV_OBJECT
CREATE TABLE IF NOT EXISTS LOV_OBJECT
(
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE,
    TABLE_NAME VARCHAR(100),
    WHERE_FILTER VARCHAR(255),
    SVC_ID INTEGER NOT NULL DEFAULT 0
);
COMMENT ON TABLE LOV_OBJECT IS 'Сущностные объекты';

-- LOV_PGE_PROP_TYPE
CREATE TABLE IF NOT EXISTS LOV_PGE_PROP_TYPE
(
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    ID_OBJ INTEGER REFERENCES LOV_OBJECT(ID),
    USE_MULTI_SELECT BOOLEAN NOT NULL DEFAULT FALSE
);
COMMENT ON TABLE LOV_PGE_PROP_TYPE IS 'Типы свойств';

CREATE INDEX IF NOT EXISTS LOV_PT_OBJ_IDX ON LOV_PGE_PROP_TYPE(ID_OBJ);

-- LOV_PGE_PROPERTY
CREATE TABLE IF NOT EXISTS LOV_PGE_PROPERTY
(
    ID INTEGER NOT NULL PRIMARY KEY,
    CODE VARCHAR(20) NOT NULL UNIQUE,
    NAME VARCHAR(100) UNIQUE NOT NULL,
    ID_PROP_TYPE INTEGER NOT NULL REFERENCES LOV_PGE_PROP_TYPE(ID)
);
COMMENT ON TABLE LOV_PGE_PROPERTY IS 'Свойства';

CREATE INDEX IF NOT EXISTS LOV_P_PT_IDX ON LOV_PGE_PROPERTY(ID_PROP_TYPE);

-- LOV_PGE_PROPERTY_GROUP
CREATE TABLE IF NOT EXISTS LOV_PGE_PROPERTY_GROUP
(
    ID INTEGER NOT NULL PRIMARY KEY,
    CODE VARCHAR(20) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    LAYER_SEL_QUERY TEXT,
    SVC_ID INTEGER NOT NULL DEFAULT 0
);
COMMENT ON TABLE LOV_PGE_PROPERTY_GROUP IS 'Группа свойств';

-- LOV_PGE_PG_LAYER
CREATE TABLE IF NOT EXISTS LOV_PGE_PG_LAYER
(
    ID    INTEGER NOT NULL PRIMARY KEY,
    ID_PG INTEGER NOT NULL REFERENCES LOV_PGE_PROPERTY_GROUP(ID),
    SEL_VALUE VARCHAR(255) NOT NULL
);
COMMENT ON TABLE LOV_PGE_PG_LAYER IS 'Слой группы свойств';

CREATE INDEX IF NOT EXISTS LOV_PGL_PG_IDX ON LOV_PGE_PG_LAYER(ID_PG);

-- LOV_PGE_PROPERTY_GROUP_DTL
CREATE TABLE IF NOT EXISTS LOV_PGE_PGL_DTL
(
    ID INTEGER NOT NULL PRIMARY KEY,
    ID_PGL INTEGER NOT NULL REFERENCES LOV_PGE_PG_LAYER(ID),
    ID_PROPERTY INTEGER NOT NULL REFERENCES LOV_PGE_PROPERTY(ID),
    PROPERTY_FORMAT VARCHAR(255),
    DEFAULT_VALUE VARCHAR(255),
    PG_ORDER INTEGER DEFAULT 0 NOT NULL
);
COMMENT ON TABLE LOV_PGE_PGL_DTL IS 'Состав группы свойств в слое';

DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'lov_pge_prp_grp_dt_uk') THEN
            ALTER TABLE LOV_PGE_PGL_DTL
                ADD CONSTRAINT LOV_PGE_PRP_GRP_DT_UK UNIQUE(ID_PGL, ID_PROPERTY);
        END IF;
    END $$;

CREATE INDEX IF NOT EXISTS LOV_PGL_DTL_PGL_UDX ON LOV_PGE_PGL_DTL(ID_PGL);
CREATE INDEX IF NOT EXISTS LOV_PGL_DTL_PRP_UDX ON LOV_PGE_PGL_DTL(ID_PROPERTY);
CREATE INDEX IF NOT EXISTS LOV_PGL_DTL_ORD_UDX ON LOV_PGE_PGL_DTL(PG_ORDER);

-- LOV_PROPERTY_GROUP_TO_OBJ
CREATE TABLE IF NOT EXISTS LOV_PGE_PG_TO_OBJ
(
    ID INTEGER NOT NULL PRIMARY KEY,
    ID_OBJ INTEGER NOT NULL REFERENCES LOV_OBJECT(ID),
    CODE_PG VARCHAR(20) NOT NULL
);
COMMENT ON TABLE LOV_PGE_PG_TO_OBJ IS 'Связь групп свойств с сущностями';

CREATE INDEX IF NOT EXISTS LOV_PG_TO_OBJ_OBJ_IDX ON LOV_PGE_PG_TO_OBJ(ID_OBJ);
CREATE INDEX IF NOT EXISTS LOV_PG_TO_OBJ_CODE_IDX ON LOV_PGE_PG_TO_OBJ(CODE_PG);

DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'lov_pg_to_obj_uk') THEN
            ALTER TABLE LOV_PGE_PG_TO_OBJ
                ADD CONSTRAINT LOV_PG_TO_OBJ_UK UNIQUE(ID_OBJ, CODE_PG);
        END IF;
    END $$;

-- PGE_PROPS
CREATE TABLE IF NOT EXISTS PGE_PROPS
(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    ID_PGL INTEGER NOT NULL REFERENCES LOV_PGE_PG_LAYER(ID),
    ID_PROPERTY INTEGER NOT NULL REFERENCES LOV_PGE_PROPERTY(ID),
    ID_ENTITY BIGINT NOT NULL,
    PROPERTY_VALUE VARCHAR(255),
    CREATED_BY  VARCHAR(20)  NOT NULL,
    CREATED_AT  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY  VARCHAR(20),
    UPDATED_AT  TIMESTAMPTZ
);
COMMENT ON TABLE PGE_PROPS IS 'Значения свойств';

DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pge_props_uk') THEN
            ALTER TABLE PGE_PROPS
                ADD CONSTRAINT PGE_PROPS_UK UNIQUE(ID_PGL, ID_PROPERTY, ID_ENTITY);
        END IF;
    END $$;

CREATE INDEX IF NOT EXISTS PGE_PROPS_PGL_IDX ON PGE_PROPS(ID_PGL);
CREATE INDEX IF NOT EXISTS PGE_PROPS_PRP_IDX ON PGE_PROPS(ID_PROPERTY);
CREATE INDEX IF NOT EXISTS PGE_PROPS_ENT_IDX ON PGE_PROPS(ID_ENTITY);

-- PGE_PROPS_OIP
CREATE TABLE IF NOT EXISTS PGE_PROPS_OIP
(
    ID BIGINT NOT NULL PRIMARY KEY,
    ID_OIP INTEGER NOT NULL REFERENCES KLF_OIP(ID)
);
COMMENT ON TABLE PGE_PROPS_OIP IS 'Связь свойств с ОИС';

CREATE INDEX IF NOT EXISTS PGE_PROPS_OIP_OIP_IDX ON PGE_PROPS_OIP(ID_OIP);

-- Составной индекс для быстрого поиска значений свойств
CREATE INDEX IF NOT EXISTS pge_props_composite_idx
    ON PGE_PROPS(id_pgl, id_property, id_entity)
    INCLUDE (property_value);

-- Индекс для фильтрации по CODE
CREATE INDEX IF NOT EXISTS lov_pge_pg_code_idx
    ON LOV_PGE_PROPERTY_GROUP(code)
    INCLUDE (layer_sel_query);

-- Частичный индекс для справочных типов
CREATE INDEX IF NOT EXISTS lov_pge_prop_type_ref_idx
    ON LOV_PGE_PROP_TYPE(id_obj)
    WHERE id_obj IS NOT NULL;