-- KLF_RIGHT_TYPE
CREATE TABLE IF NOT EXISTS KLF_RIGHT_TYPE (
    ID          SERIAL PRIMARY KEY,
    ID_PARENT   INTEGER NULL REFERENCES KLF_RIGHT_TYPE(ID) ON DELETE RESTRICT,
    NAME        VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1023),
    CREATED_BY  VARCHAR(20)  NOT NULL,
    CREATED_AT  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UPDATED_BY  VARCHAR(20),
    UPDATED_AT  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS IDX_KLF_RIGHT_TYPE_PARENT ON KLF_RIGHT_TYPE(ID_PARENT);
CREATE INDEX IF NOT EXISTS IDX_KLF_RIGHT_TYPE_NAME ON KLF_RIGHT_TYPE(NAME);

-- Корневой элемент (ID=0, parent NULL) — создаём, если его нет
DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM KLF_RIGHT_TYPE WHERE ID = 0) THEN
            INSERT INTO KLF_RIGHT_TYPE(ID, ID_PARENT, NAME, CREATED_BY, CREATED_AT)
            VALUES (0, NULL, 'Все права', 'admin', now());
        END IF;
    END$$;

-- KLF_FEATURE_CAT_TO_RT
CREATE TABLE IF NOT EXISTS KLF_FEATURE_CAT_TO_RT (
    ID                   SERIAL PRIMARY KEY,
    ID_RIGHT_TYPE        INTEGER NOT NULL REFERENCES KLF_RIGHT_TYPE(ID) ON DELETE RESTRICT,
    ID_FEATURE_CATEGORY  INTEGER NOT NULL REFERENCES KLF_FEATURE_CATEGORY(ID) ON DELETE RESTRICT,
    ID_DEF_FEATURE       INTEGER NULL REFERENCES KLF_FEATURE_TREE(ID) ON DELETE RESTRICT,
    CREATED_BY           VARCHAR(20) NOT NULL,
    CREATED_AT           TIMESTAMPTZ NOT NULL DEFAULT now(),
    UPDATED_BY           VARCHAR(20),
    UPDATED_AT           TIMESTAMPTZ
);

-- Один тип права не должен иметь дублирующуюся категорию
CREATE UNIQUE INDEX IF NOT EXISTS UNQ_KLF_FEATURE_CAT_TO_RT ON KLF_FEATURE_CAT_TO_RT(ID_RIGHT_TYPE, ID_FEATURE_CATEGORY);

CREATE INDEX IF NOT EXISTS IDX_KLF_FEATURE_CAT_TO_RT_RT ON KLF_FEATURE_CAT_TO_RT(ID_RIGHT_TYPE);
