-- Расширение для эффективного ILIKE '%...%' по name
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- LOV_OIP_SUPER_TYPE
CREATE TABLE IF NOT EXISTS LOV_OIP_SUPER_TYPE (
    ID   SERIAL PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL
);

-- LOV_OIP_TYPE
CREATE TABLE IF NOT EXISTS LOV_OIP_TYPE (
    ID   SERIAL PRIMARY KEY,
    ID_OIP_SUPER_TYPE INTEGER NOT NULL REFERENCES LOV_OIP_SUPER_TYPE(ID),
    NAME VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS UNQ_LOV_OIP_TYPE ON LOV_OIP_TYPE(ID_OIP_SUPER_TYPE, NAME);

-- KLF_OIP
CREATE TABLE IF NOT EXISTS KLF_OIP (
    ID                SERIAL PRIMARY KEY,
    GUID              VARCHAR(255) UNIQUE,
    ID_OIP_SUPER_TYPE INTEGER NOT NULL REFERENCES LOV_OIP_SUPER_TYPE(ID),
    ID_OIP_TYPE       INTEGER NOT NULL REFERENCES LOV_OIP_TYPE(ID),
    NAME              VARCHAR(512) NOT NULL,
    PART_NUM          INTEGER NOT NULL DEFAULT 0,
    PART_COUNT        INTEGER NOT NULL DEFAULT 0,
    DURATION          INTERVAL,
    DESCRIPTION       TEXT,
    CREATED_BY        VARCHAR(20)  NOT NULL,
    CREATED_AT        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY        VARCHAR(20),
    UPDATED_AT        TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_klf_oip_super_type ON KLF_OIP(ID_OIP_SUPER_TYPE);
CREATE INDEX IF NOT EXISTS idx_klf_oip_type       ON KLF_OIP(ID_OIP_TYPE);
CREATE INDEX IF NOT EXISTS idx_klf_oip_name_trgm  ON KLF_OIP USING gin (NAME gin_trgm_ops);

-- KLF_OIP_HIERARCHY
CREATE TABLE IF NOT EXISTS KLF_OIP_HIERARCHY (
    ID         SERIAL PRIMARY KEY,
    ID_PARENT  INTEGER NOT NULL REFERENCES KLF_OIP(ID),
    ID_OIP     INTEGER NOT NULL REFERENCES KLF_OIP(ID),
    CREATED_BY VARCHAR(20)  NOT NULL,
    CREATED_AT TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_klf_oip_h_parent ON KLF_OIP_HIERARCHY(ID_PARENT);
CREATE INDEX IF NOT EXISTS idx_klf_oip_h_oip    ON KLF_OIP_HIERARCHY(ID_OIP);
CREATE UNIQUE INDEX IF NOT EXISTS UNQ_KLF_OIP_HIERARCHY ON KLF_OIP_HIERARCHY(ID_PARENT, ID_OIP);

DO $$
DECLARE
 v_id_super_type INTEGER;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM LOV_OIP_SUPER_TYPE WHERE NAME = 'Видео') THEN
       INSERT INTO LOV_OIP_SUPER_TYPE (NAME) VALUES ('Видео')
           RETURNING ID INTO v_id_super_type;

       INSERT INTO LOV_OIP_TYPE (ID_OIP_SUPER_TYPE, NAME) VALUES (v_id_super_type,'Фильм');
       INSERT INTO LOV_OIP_TYPE (ID_OIP_SUPER_TYPE, NAME) VALUES (v_id_super_type,'Сериал');
       INSERT INTO LOV_OIP_TYPE (ID_OIP_SUPER_TYPE, NAME) VALUES (v_id_super_type,'Сезон');
       INSERT INTO LOV_OIP_TYPE (ID_OIP_SUPER_TYPE, NAME) VALUES (v_id_super_type,'Серия');
       INSERT INTO LOV_OIP_TYPE (ID_OIP_SUPER_TYPE, NAME) VALUES (v_id_super_type,'Пакет');
    END IF;
END$$;