-- Расширение для эффективного ILIKE '%...%' по name
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- LOV_OIP_SUPER_TYPE
CREATE TABLE IF NOT EXISTS LOV_OIP_SUPER_TYPE (
    ID   SERIAL PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL
);

-- LOV_OIP_TYPE
CREATE TABLE IF NOT EXISTS LOV_OIP_TYPE (
    ID   SERIAL PRIMARY KEY,
    ID_OIP_SUPER_TYPE INTEGER NOT NULL REFERENCES LOV_OIP_SUPER_TYPE(ID),
    NAME VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS UNQ_LOV_OIP_TYPE ON LOV_OIP_TYPE(ID_OIP_SUPER_TYPE, NAME);

-- KLF_OIP
CREATE TABLE IF NOT EXISTS KLF_OIP (
    ID                SERIAL PRIMARY KEY,
    GUID              VARCHAR(255) UNIQUE,
    ID_OIP_SUPER_TYPE INTEGER NOT NULL REFERENCES LOV_OIP_SUPER_TYPE(ID),
    ID_OIP_TYPE       INTEGER NOT NULL REFERENCES LOV_OIP_TYPE(ID),
    NAME              VARCHAR(512) NOT NULL,
    PART_NUM          INTEGER NOT NULL DEFAULT 0,
    PART_COUNT        INTEGER NOT NULL DEFAULT 0,
    DURATION          INTERVAL,
    DESCRIPTION       TEXT,
    CREATED_BY        VARCHAR(20)  NOT NULL,
    CREATED_AT        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY        VARCHAR(20),
    UPDATED_AT        TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_klf_oip_super_type ON KLF_OIP(ID_OIP_SUPER_TYPE);
CREATE INDEX IF NOT EXISTS idx_klf_oip_type       ON KLF_OIP(ID_OIP_TYPE);
CREATE INDEX IF NOT EXISTS idx_klf_oip_name_trgm  ON KLF_OIP USING gin (NAME gin_trgm_ops);

-- KLF_OIP_HIERARCHY
CREATE TABLE IF NOT EXISTS KLF_OIP_HIERARCHY (
    ID         SERIAL PRIMARY KEY,
    ID_PARENT  INTEGER NOT NULL REFERENCES KLF_OIP(ID),
    ID_OIP     INTEGER NOT NULL REFERENCES KLF_OIP(ID),
    CREATED_BY VARCHAR(20)  NOT NULL,
    CREATED_AT TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_klf_oip_h_parent ON KLF_OIP_HIERARCHY(ID_PARENT);
CREATE INDEX IF NOT EXISTS idx_klf_oip_h_oip    ON KLF_OIP_HIERARCHY(ID_OIP);
CREATE UNIQUE INDEX IF NOT EXISTS UNQ_KLF_OIP_HIERARCHY ON KLF_OIP_HIERARCHY(ID_PARENT, ID_OIP);

DO $$
DECLARE
 v_id_super_type INTEGER;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM LOV_OIP_SUPER_TYPE WHERE NAME = 'Видео') THEN
       INSERT INTO LOV_OIP_SUPER_TYPE (NAME) VALUES ('Видео')
           RETURNING ID INTO v_id_super_type;

       INSERT INTO LOV_OIP_TYPE (ID_OIP_SUPER_TYPE, NAME) VALUES (v_id_super_type,'Фильм');
       INSERT INTO LOV_OIP_TYPE (ID_OIP_SUPER_TYPE, NAME) VALUES (v_id_super_type,'Сериал');
       INSERT INTO LOV_OIP_TYPE (ID_OIP_SUPER_TYPE, NAME) VALUES (v_id_super_type,'Сезон');
       INSERT INTO LOV_OIP_TYPE (ID_OIP_SUPER_TYPE, NAME) VALUES (v_id_super_type,'Серия');
       INSERT INTO LOV_OIP_TYPE (ID_OIP_SUPER_TYPE, NAME) VALUES (v_id_super_type,'Пакет');
    END IF;
END$$;

-- Добавить колонки
ALTER TABLE KLF_OIP ADD COLUMN IF NOT EXISTS HAS_CHILDREN BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE KLF_OIP ADD COLUMN IF NOT EXISTS HAS_PARENT BOOLEAN NOT NULL DEFAULT FALSE;

-- partial индексы для оптимизации запросов
CREATE INDEX IF NOT EXISTS idx_klf_oip_has_children
    ON KLF_OIP(HAS_CHILDREN) WHERE HAS_CHILDREN = TRUE;

CREATE INDEX IF NOT EXISTS idx_klf_oip_is_leaf
    ON KLF_OIP(HAS_CHILDREN) WHERE HAS_CHILDREN = FALSE;

CREATE INDEX IF NOT EXISTS idx_klf_oip_has_parent
    ON KLF_OIP(HAS_PARENT) WHERE HAS_PARENT = TRUE;

CREATE INDEX IF NOT EXISTS idx_klf_oip_is_root
    ON KLF_OIP(HAS_PARENT) WHERE HAS_PARENT = FALSE;

-- Функция триггера для автоматического обновления флагов
CREATE OR REPLACE FUNCTION update_hierarchy_flags() RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        -- При добавлении связи обновить флаги
        UPDATE KLF_OIP SET HAS_CHILDREN = TRUE WHERE ID = NEW.ID_PARENT;
        UPDATE KLF_OIP SET HAS_PARENT = TRUE WHERE ID = NEW.ID_OIP;

    ELSIF TG_OP = 'DELETE' THEN
        -- При удалении связи проверить, остались ли другие связи
        UPDATE KLF_OIP
        SET HAS_CHILDREN = EXISTS(
            SELECT 1 FROM KLF_OIP_HIERARCHY WHERE ID_PARENT = OLD.ID_PARENT
        )
        WHERE ID = OLD.ID_PARENT;

        UPDATE KLF_OIP
        SET HAS_PARENT = EXISTS(
            SELECT 1 FROM KLF_OIP_HIERARCHY WHERE ID_OIP = OLD.ID_OIP
        )
        WHERE ID = OLD.ID_OIP;

    ELSIF TG_OP = 'UPDATE' THEN
        -- При изменении связи обновить все 4 записи
        IF OLD.ID_PARENT IS DISTINCT FROM NEW.ID_PARENT OR OLD.ID_OIP IS DISTINCT FROM NEW.ID_OIP THEN
            -- Проверить старого родителя
            UPDATE KLF_OIP
            SET HAS_CHILDREN = EXISTS(
                SELECT 1 FROM KLF_OIP_HIERARCHY WHERE ID_PARENT = OLD.ID_PARENT
            )
            WHERE ID = OLD.ID_PARENT;

            -- Установить флаг для нового родителя
            UPDATE KLF_OIP SET HAS_CHILDREN = TRUE WHERE ID = NEW.ID_PARENT;

            -- Проверить старого потомка
            UPDATE KLF_OIP
            SET HAS_PARENT = EXISTS(
                SELECT 1 FROM KLF_OIP_HIERARCHY WHERE ID_OIP = OLD.ID_OIP
            )
            WHERE ID = OLD.ID_OIP;

            -- Установить флаг для нового потомка
            UPDATE KLF_OIP SET HAS_PARENT = TRUE WHERE ID = NEW.ID_OIP;
        END IF;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION update_hierarchy_flags() IS
    'Автоматически обновляет флаги HAS_CHILDREN и HAS_PARENT в таблице KLF_OIP при изменении иерархии';

DROP TRIGGER IF EXISTS trg_update_hierarchy_flags ON KLF_OIP_HIERARCHY;

CREATE TRIGGER trg_update_hierarchy_flags
    AFTER INSERT OR UPDATE OR DELETE ON KLF_OIP_HIERARCHY
    FOR EACH ROW EXECUTE FUNCTION update_hierarchy_flags();

COMMENT ON COLUMN KLF_OIP.HAS_CHILDREN IS
    'Флаг наличия потомков в таблице KLF_OIP_HIERARCHY';

COMMENT ON COLUMN KLF_OIP.HAS_PARENT IS
    'Флаг наличия родителя в таблице KLF_OIP_HIERARCHY';

-- Обновить статистику таблицы для оптимизатора
ANALYZE KLF_OIP;
ANALYZE KLF_OIP_HIERARCHY;