CREATE TABLE IF NOT EXISTS KLF_ORGANIZATION (
    ID          SERIAL PRIMARY KEY,
    GUID        VARCHAR(255) UNIQUE,
    NAME        VARCHAR(255) NOT NULL,
    CREATED_BY  VARCHAR(20)  NOT NULL,
    CREATED_AT  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY  VARCHAR(20),
    UPDATED_AT  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS KLF_COUNTERPARTY (
    ID          SERIAL PRIMARY KEY,
    GUID        VARCHAR(255) UNIQUE,
    NAME        VARCHAR(255) NOT NULL,
    ID_ORG_REF  INT REFERENCES KLF_ORGANIZATION(ID),
    CREATED_BY  VARCHAR(20)  NOT NULL,
    CREATED_AT  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY  VARCHAR(20),
    UPDATED_AT  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_klf_cpart_guid ON KLF_COUNTERPARTY(GUID);
CREATE INDEX IF NOT EXISTS idx_klf_cpart_name_trgm  ON KLF_COUNTERPARTY USING gin (NAME gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_klf_org_guid ON KLF_ORGANIZATION(GUID);
CREATE INDEX IF NOT EXISTS idx_klf_org_name_trgm  ON KLF_ORGANIZATION USING gin (NAME gin_trgm_ops);
