apiVersion: v1
kind: Secret
metadata:
  name: rf-catalog-secret
  namespace: develop
type: Opaque
data:
  # echo -n "users_db" | base64 -> dXNlcnNfZGI=
  postgres-password: cmYtT3duZXIyNQ==
  postgres-user: cmlnaHRzZmxvdw==
  swagger-secret: bW1LLXc3d3hDZm1FdzdTdlBDbW1YbmN1SUZ4UWM2eEwtNjUxNWM0VUIwaw==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rf-catalog-svc
data:
  hostname: catalog-svc
  hostname-external: rights.flow.me
  profiles: local,kafka
  catalog-db: pg-catalog-db-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rf-catalog-svc
  labels:
    app: rf-catalog-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rf-catalog-svc
  template:
    metadata:
      name: rf-catalog-svc
      labels:
        app: rf-catalog-svc
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/api/catalog/v1/actuator/prometheus"
        prometheus.io/port: "8081" # <-- порт приложения
    spec:
      #      hostAliases:
      #        - ip: "192.168.1.22"
      #          hostnames:
      #            - "gitlab.micxem"
      containers:
        - name: rf-catalog-svc
          image: gitlab.micxem:5050/rights-flow/rf-catalog-svc:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          args: [ "--spring.profiles.active=$(RF_CATALOG_SVC_PROFILES)"]
          env:
            - name: RF_CATALOG_SVC_PROFILES
              valueFrom:
                configMapKeyRef:
                  name: rf-catalog-svc
                  key: profiles
            - name: RF_EUREKA_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: rf-eureka-svc
                  key: serviceURL
            - name: RF_CATALOG_SVC_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: rf-catalog-svc
                  key: hostname
            - name: RF_CATALOG_SVC_HOSTNAME_EXTERNAL
              valueFrom:
                configMapKeyRef:
                  name: rf-catalog-svc
                  key: hostname-external
            - name: RF_AUTH_SVC_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: rf-auth-svc
                  key: hostname
            - name: RF_CONFIG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: rf-config-svc
                  key: serviceURL
            - name: RF_PG_CATALOG_DB_SVC
              valueFrom:
                configMapKeyRef:
                  name: rf-catalog-svc
                  key: catalog-db
            - name: PG_DB_USER
              valueFrom:
                secretKeyRef:
                  name: rf-catalog-secret
                  key: postgres-user
            - name: PG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rf-catalog-secret
                  key: postgres-password
            - name: SWAGGER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: rf-catalog-secret
                  key: swagger-secret
            - name: RF_KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-props
                  key: brokers
            - name: RF_SCHEMA_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: kafka-props
                  key: schema-registry-url

          readinessProbe:
            httpGet:
              path: /api/catalog/v1/actuator/health/readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /api/catalog/v1/actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 15
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1024Mi"
      restartPolicy: Always
      imagePullSecrets:
        - name: gitlab-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-svc
  labels:
    app: rf-catalog-svc
spec:
  selector:
    app: rf-catalog-svc
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081